#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# only branches and files git completion
__git_files () {
    _wanted files expl 'local files' _files
}

alias j=fasd_cd

alias ec="emacsclient --no-wait"
alias bdi='eval "$(boot2docker shellinit)"'
alias bds='boot2docker ssh'
alias bd='boot2docker'

PERL_MB_OPT="--install_base \"/home/henro/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/henro/perl5"; export PERL_MM_OPT;
PERL5LIB="/home/henro/perl5/lib/perl5"; export PERL5LIB;